source 'https://rubygems.org'

ruby '2.2.3'

gem 'sinatra'
gem 'rack'
gem 'thin'
gem 'mongoid', '~> 5.0.0beta'
gem 'bson_ext'
gem 'pry'
gem 'sinatra-assetpack', '0.1.5'
gem 'httparty'
gem 'json'
gem 'unicorn'
gem 'tilt', '~> 1.4.1'
gem 'iconv', '~> 1.0.3'
gem 'rack-test'
gem 'multi_json'
gem 'apns'
gem 'dragonfly'
gem 'dragonfly-s3_data_store'
gem 'factory_girl'
gem 'aws-sdk', '~> 2'
gem 'jwt'
gem 'postmark'
gem 'premailer'

group :test do
	gem 'turn'
	gem 'rake'
	gem 'minitest-reporters'
	gem 'mocha'
	gem 'm'
end
